# Generated by Django 2.1.3 on 2018-11-30 08:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('article_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='帖子id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('uid', models.CharField(max_length=100, verbose_name='发帖人')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='发帖时间')),
                ('addr', models.CharField(default='南宁学院', max_length=200, verbose_name='发生地点')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
    ]
