# Generated by Django 2.1.3 on 2018-12-11 05:04

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('article_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='帖子id')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('uid', models.CharField(max_length=100, verbose_name='发帖人')),
                ('newsdate', models.DateTimeField(auto_now=True, verbose_name='发帖时间')),
                ('releasedate', models.DateTimeField(default=datetime.datetime.now, verbose_name='发帖时间')),
                ('addr', models.CharField(default='南宁学院', max_length=200, verbose_name='发生地点')),
                ('item', models.CharField(default='未知', max_length=20, verbose_name='物品名')),
                ('lostdate', models.CharField(default='未知', max_length=100, verbose_name='遗失/拾取时间')),
                ('reply_num', models.IntegerField(default=0, verbose_name='回复数量')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('comment_auth', models.CharField(max_length=100, verbose_name='评论作者')),
                ('comment_date', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('read', models.BooleanField(default=False, verbose_name='消息已读')),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexPage.article')),
            ],
            options={
                'verbose_name': '评论内容',
                'verbose_name_plural': '评论内容',
            },
        ),
    ]
