# Generated by Django 2.1.3 on 2018-12-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_to',
            field=models.CharField(default='', max_length=100, verbose_name='原帖作者'),
            preserve_default=False,
        ),
    ]
