# Generated by Django 2.1.3 on 2018-12-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0002_comment_comment_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_article_title',
            field=models.CharField(default='', max_length=100, verbose_name='原帖标题'),
            preserve_default=False,
        ),
    ]
