# Generated by Django 2.1.5 on 2019-04-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0003_comment_comment_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.BooleanField(default=0, verbose_name='状态'),
        ),
    ]
