# Generated by Django 2.1.5 on 2019-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0007_auto_20190423_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_verify',
            field=models.IntegerField(default=0, verbose_name='审核状态[0未审核 1通过 2不通过]'),
        ),
    ]
