# Generated by Django 2.1.5 on 2019-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0008_auto_20190426_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
