# Generated by Django 2.1.5 on 2019-04-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0011_article_lost_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='lost_state',
            new_name='lost_type',
        ),
    ]
