# Generated by Django 2.1.5 on 2019-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0013_comment_auth_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='auth_nickname',
            field=models.CharField(default='未设昵称', max_length=10, verbose_name='昵称'),
        ),
    ]
