# Generated by Django 2.1.5 on 2019-05-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0015_auto_20190509_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='Notices_content',
            field=models.TextField(default='风平浪静的一天,没有公告呢。', max_length=150, verbose_name='公告内容'),
        ),
    ]
