# Generated by Django 2.1.3 on 2018-12-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_table',
            name='about',
            field=models.CharField(default='', max_length=200, verbose_name='签名'),
        ),
        migrations.AddField(
            model_name='message_table',
            name='addr',
            field=models.CharField(default='', max_length=30, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='message_table',
            name='male',
            field=models.CharField(default='隐藏', max_length=2, verbose_name='性别'),
        ),
    ]
