# Generated by Django 2.1.3 on 2018-12-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20181204_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_table',
            name='headImage',
            field=models.ImageField(default='/static/usermess/images/head.jpg', max_length=200, upload_to='media/upload/head/', verbose_name='头像'),
        ),
    ]
