# Generated by Django 2.1.3 on 2018-12-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_message_table_headimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_table',
            name='headImage',
            field=models.ImageField(default='/static/usermess/images/head.jpg', max_length=200, upload_to='upload/head/', verbose_name='头像'),
        ),
    ]
