# Generated by Django 2.1.5 on 2019-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20181214_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_table',
            name='headImage',
            field=models.ImageField(default='/static/usermess/images/head.jpg', max_length=200, upload_to='upload/head/', verbose_name='头像'),
        ),
    ]
