# Generated by Django 2.1.5 on 2019-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_auto_20190426_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_table',
            name='QQ',
            field=models.CharField(default='无', max_length=200, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='message_table',
            name='WeChat',
            field=models.CharField(default='无', max_length=200, verbose_name='微信'),
        ),
    ]
