# Generated by Django 2.1.5 on 2019-04-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0007_auto_20190427_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_table',
            old_name='WeChat',
            new_name='WeChats',
        ),
    ]
